package com.eyesopencrew;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 * @author Beny Green - gacksecurity.blogspot.com
 *
 * EyesOpenCrew
 */
public class Bsniper extends javax.swing.JFrame {

    /**
     * Creates new form Bsniper
     */
    public int def = 0 ;
    private String vLinkcc;
    private String vOS;
    private String vPlatform;
    private String vPlugins;
    private String vUserAgent;
    private String vVBScript;
    private String vVersion;
    private String vActiveX;
    private String vAttack_URL;
    public  String vBrowser;
    private String vFlash;
    private String vJava;

    public String getvLinkcc() {
        return vLinkcc;
    }

    public void setvLinkcc(String vLinkcc) {
        this.vLinkcc = vLinkcc;
    }

    public String getvOS() {
        return vOS;
    }

    public void setvOS(String vOS) {
        this.vOS = vOS;
    }

    public String getvPlatform() {
        return vPlatform;
    }

    public void setvPlatform(String vPlatform) {
        this.vPlatform = vPlatform;
    }

    public String getvPlugins() {
        return vPlugins;
    }

    public void setvPlugins(String vPlugins) {
        this.vPlugins = vPlugins;
    }

    public String getvUserAgent() {
        return vUserAgent;
    }

    public void setvUserAgent(String vUserAgent) {
        this.vUserAgent = vUserAgent;
    }

    public String getvVBScript() {
        return vVBScript;
    }

    public void setvVBScript(String vVBScript) {
        this.vVBScript = vVBScript;
    }

    public String getvVersion() {
        return vVersion;
    }

    public void setvVersion(String vVersion) {
        this.vVersion = vVersion;
    }

    public String getvActiveX() {
        return vActiveX;
    }

    public void setvActiveX(String vActiveX) {
        this.vActiveX = vActiveX;
    }

    public String getvAttack_URL() {
        return vAttack_URL;
    }

    public void setvAttack_URL(String vAttack_URL) {
        this.vAttack_URL = vAttack_URL;
    }

    public String getvBrowser() {
        return vBrowser;
    }

    public void setvBrowser(String vBrowser) {
        this.vBrowser = vBrowser;
    }

    public String getvFlash() {
        return vFlash;
    }

    public void setvFlash(String vFlash) {
        this.vFlash = vFlash;
    }

    public String getvJava() {
        return vJava;
    }

    public void setvJava(String vJava) {
        this.vJava = vJava;
    }
    
    public Bsniper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBrowser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jUserAgent = new javax.swing.JTextField();
        jVersion = new javax.swing.JTextField();
        jOS = new javax.swing.JTextField();
        exBrowser = new javax.swing.JLabel();
        exUserAgent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPlatform = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jActiveX = new javax.swing.JTextField();
        jFlash = new javax.swing.JTextField();
        jJava = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jVBScript = new javax.swing.JTextField();
        jPlugins = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jAttack_URL = new javax.swing.JTextField();
        jLinkcc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jValidate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add a new profile to Sniper");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Browser");

        jLabel2.setText("UserAgent");

        jLabel3.setText("Version");

        jLabel4.setText("OS");

        jLabel5.setText("Platform");

        jLabel6.setText("ActiveX");

        jLabel7.setText("Flash");

        jLabel8.setText("Java");

        jLabel9.setText("VBScript");

        jLabel10.setText("Plugins");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Attack_URL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Link_cc*");

        jLabel13.setText("* : CC = Command Code. Link_CC = Link to a Command Code.");

        jBrowser.setText("*");
        jBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowserActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("Properties                              Values                                     Examples");

        jUserAgent.setText("*");

        jVersion.setText("*");

        jOS.setText("*");

        exBrowser.setText("IE, FF, O, C");

        exUserAgent.setText("MSIE,Firefox");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Just keep in mind that the defined profile will be\nmatching only if the String you are looking for exist \nin the exact order in the property value for the \ntargeted zombie. This values must be recognized \nby BeEF. Here is the regex in use: (.*|\\s)+value+(\\s|.*)");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel16.setText("6, 8, 15");

        jLabel17.setText("Win, Andro, inux");

        jPlatform.setText("*");

        jLabel18.setText("i3");

        jActiveX.setText("*");

        jFlash.setText("*");

        jJava.setText("*");

        jLabel19.setText("Yes, No");

        jLabel20.setText("Yes, No");

        jLabel21.setText("Y, N");

        jVBScript.setText("*");

        jPlugins.setText("*");

        jLabel22.setText("Adob, Silv, 17u1");

        jLabel23.setText("http://attack.com");

        jAttack_URL.setText("http://");

        jLinkcc.setText("*");
        jLinkcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLinkccActionPerformed(evt);
            }
        });

        jLabel24.setText("0,1,2");

        jValidate.setText("Add");
        jValidate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jValidateMouseClicked(evt);
            }
        });
        jValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBrowser)
                            .addComponent(jUserAgent)
                            .addComponent(jVersion)
                            .addComponent(jOS)
                            .addComponent(jPlatform)
                            .addComponent(jActiveX)
                            .addComponent(jFlash)
                            .addComponent(jJava)
                            .addComponent(jVBScript)
                            .addComponent(jPlugins)
                            .addComponent(jAttack_URL, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jLinkcc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(exBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exUserAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addComponent(jLabel24)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exBrowser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jUserAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exUserAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPlatform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jActiveX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFlash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jVBScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPlugins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel23)
                    .addComponent(jAttack_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLinkcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValidate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrowserActionPerformed

    private void jLinkccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLinkccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLinkccActionPerformed

    private void jValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidateActionPerformed
   /*    this.vActiveX = this.jActiveX.getText() ;
       this.vLinkcc = this.jLinkcc.getText() ;
       this.vOS = this.jOS.getText() ;
       this.vPlatform = this.jPlatform.getText() ;
       this.vPlugins = this.jPlugins.getText() ;
       this.vUserAgent = this.jUserAgent.getText() ;
       this.vVersion = this.jVersion.getText() ;
       this.vVBScript = this.jVBScript.getText();
       this.vAttack_URL = this.jAttack_URL.getText() ;
       this.vBrowser = this.jBrowser.getText() ;
       this.vFlash = this.jFlash.getText() ;
       this.vJava = this.jJava.getText();
       this.setVisible(true);
       this.def = 1 ;
      // String a = this.getvBrowser();
       // System.out.println(a);
        this.dispose();
         System.exit(0); 
       */
    }//GEN-LAST:event_jValidateActionPerformed

    private void jValidateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jValidateMouseClicked
       this.vActiveX = this.jActiveX.getText() ;
       this.vLinkcc = this.jLinkcc.getText() ;
       this.vOS = this.jOS.getText() ;
       this.vPlatform = this.jPlatform.getText() ;
       this.vPlugins = this.jPlugins.getText() ;
       this.vUserAgent = this.jUserAgent.getText() ;
       this.vVersion = this.jVersion.getText() ;
       this.vVBScript = this.jVBScript.getText();
       this.vAttack_URL = this.jAttack_URL.getText() ;
       this.vBrowser = this.jBrowser.getText() ;
       this.vFlash = this.jFlash.getText() ;
       this.vJava = this.jJava.getText();
       this.setVisible(false);
       
        //String a = this.getvBrowser();
       // System.out.println(a);
    //    this.dispose();
     //    System.exit(0); 
    }//GEN-LAST:event_jValidateMouseClicked

    /**
     * @param args the command line arguments
     */
    public void displayForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bsniper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bsniper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bsniper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bsniper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bsniper().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exBrowser;
    private javax.swing.JLabel exUserAgent;
    private javax.swing.JTextField jActiveX;
    private javax.swing.JTextField jAttack_URL;
    private javax.swing.JTextField jBrowser;
    private javax.swing.JTextField jFlash;
    private javax.swing.JTextField jJava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLinkcc;
    private javax.swing.JTextField jOS;
    private javax.swing.JTextField jPlatform;
    private javax.swing.JTextField jPlugins;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jUserAgent;
    private javax.swing.JTextField jVBScript;
    private javax.swing.JButton jValidate;
    private javax.swing.JTextField jVersion;
    // End of variables declaration//GEN-END:variables

    public JTextField getjActiveX() {
        return jActiveX;
    }

    public void setjActiveX(JTextField jActiveX) {
        this.jActiveX = jActiveX;
    }

    public JTextField getjAttack_URL() {
        return jAttack_URL;
    }

    public void setjAttack_URL(JTextField jAttack_URL) {
        this.jAttack_URL = jAttack_URL;
    }

    public JTextField getjBrowser() {
        return jBrowser;
    }

    public void setjBrowser(JTextField jBrowser) {
        this.jBrowser = jBrowser;
    }

    public JTextField getjFlash() {
        return jFlash;
    }

    public void setjFlash(JTextField jFlash) {
        this.jFlash = jFlash;
    }

    public JTextField getjJava() {
        return jJava;
    }

    public void setjJava(JTextField jJava) {
        this.jJava = jJava;
    }

    public JTextField getjLinkcc() {
        return jLinkcc;
    }

    public void setjLinkcc(JTextField jLinkcc) {
        this.jLinkcc = jLinkcc;
    }

    public JTextField getjOS() {
        return jOS;
    }

    public void setjOS(JTextField jOS) {
        this.jOS = jOS;
    }

    public JTextField getjPlatform() {
        return jPlatform;
    }

    public void setjPlatform(JTextField jPlatform) {
        this.jPlatform = jPlatform;
    }

    public JTextField getjPlugins() {
        return jPlugins;
    }

    public void setjPlugins(JTextField jPlugins) {
        this.jPlugins = jPlugins;
    }

    public JTextField getjUserAgent() {
        return jUserAgent;
    }

    public void setjUserAgent(JTextField jUserAgent) {
        this.jUserAgent = jUserAgent;
    }

    public JTextField getjVBScript() {
        return jVBScript;
    }

    public void setjVBScript(JTextField jVBScript) {
        this.jVBScript = jVBScript;
    }

    public JButton getjValidate() {
        return jValidate;
    }

    public void setjValidate(JButton jValidate) {
        this.jValidate = jValidate;
    }

    public JTextField getjVersion() {
        return jVersion;
    }

    public void setjVersion(JTextField jVersion) {
        this.jVersion = jVersion;
    }

    public int getDef() {
        return def;
    }

    public void setDef(int def) {
        this.def = def;
    }

}
